### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by eeeecw** [Fansirsqi/TextureUnpacker#2]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/23431254/214539563-f75b251f-f645-4ed8-8bca-8b92e16ef2cb.png">

**Comment by Fansirsqi** [comment]
这是我的系统版本，按理说不会出现这状况，

因为是python编译的，实在不行你可以你试试直接跑py脚本吧

![image](https://user-images.githubusercontent.com/38542005/215978012-e53dded3-e3c9-489c-875f-1fce1f6e10a4.png)
